[workspace]
resolver = "2"

members = [
	"awk",
	"calc",
	"datetime",
	"dev",
	"display",
	"file",
	"fs",
	"ftw",
	"m4",
	"m4/test-manager",
	"gettext-rs",
	"misc",
	"pathnames",
	"plib",
	"process",
	"sccs",
	"screen",
	"sys",
	"text",
	"tree",
	"users",
	"xform",
	"i18n"
]

[workspace.dependencies]
atty = "0.2"
clap = { version = "4", default-features = false, features = ["std", "derive", "help", "usage", "error-context", "cargo"] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
libc = "0.2"
regex = "1.10"
gettext-rs = { path = "./gettext-rs" }
errno = "0.3"

[workspace.lints.clippy]
all = {level = "deny", priority = -1}

assign_op_pattern = "warn"
bool_comparison = "warn"
clone_on_copy = "warn"
collapsible_else_if = "warn"
collapsible_if = "warn"
comparison_chain = "warn"
derivable_impls = "warn"
derived_hash_with_manual_eq = "warn"
enum_variant_names = "allow"
format_in_format_args = "warn"
if_same_then_else = "warn"
int_plus_one = "warn"
large_enum_variant = "warn"
len_zero = "warn"
let_and_return = "warn"
manual_find = "warn"
manual_flatten = "warn"
manual_map = "warn"
manual_unwrap_or = "warn"
manual_unwrap_or_default = "warn"
match_like_matches_macro = "warn"
needless_lifetimes = "warn"
needless_range_loop = "warn"
new_without_default = "warn"
nonminimal_bool = "warn"
not_unsafe_ptr_arg_deref = "warn"
precedence = "warn"
redundant_field_names = "warn"
redundant_pattern_matching = "allow"
redundant_static_lifetimes = "warn"
result_large_err = "warn"
single_match = "warn"
suspicious_open_options = "warn"
too_many_arguments = "warn"
type_complexity = "warn"
unnecessary_cast = "warn"
unnecessary_filter_map = "warn"
unwrap_or_default = "warn"
upper_case_acronyms = "warn"
while_let_loop = "allow"
wrong_self_convention = "warn"
