[package]
name = "posixutils-tree"
version = "0.2.0"
edition = "2021"
authors = ["Jeff Garzik"]
license = "MIT"
repository = "https://github.com/rustcoreutils/posixutils-rs.git"

[dependencies]
plib = { path = "../plib" }
ftw = { path = "../ftw" }
clap.workspace = true
gettext-rs.workspace = true
libc.workspace = true
regex.workspace = true
chrono.workspace = true
atty.workspace = true
errno.workspace = true

[dev-dependencies]
tempfile = "3.10"

[features]
posixutils_test_all = []
requires_root = []

[[bin]]
name = "chgrp"
path = "./chgrp.rs"

[[bin]]
name = "chmod"
path = "./chmod.rs"

[[bin]]
name = "chown"
path = "./chown.rs"

[[bin]]
name = "cp"
path = "./cp.rs"

[[bin]]
name = "du"
path = "./du.rs"

[[bin]]
name = "link"
path = "./link.rs"

[[bin]]
name = "ln"
path = "./ln.rs"

[[bin]]
name = "ls"
path = "./ls.rs"

[[bin]]
name = "mkdir"
path = "./mkdir.rs"

[[bin]]
name = "mkfifo"
path = "./mkfifo.rs"

[[bin]]
name = "mv"
path = "./mv.rs"

[[bin]]
name = "readlink"
path = "./readlink.rs"

[[bin]]
name = "rm"
path = "./rm.rs"

[[bin]]
name = "rmdir"
path = "./rmdir.rs"

[[bin]]
name = "touch"
path = "./touch.rs"

[[bin]]
name = "unlink"
path = "./unlink.rs"

[lints]
workspace = true
