[package]
name = "posixutils-xform"
version = "0.2.0"
edition = "2021"
authors = ["Jeff Garzik"]
license = "MIT"
repository = "https://github.com/rustcoreutils/posixutils-rs.git"

[dependencies]
plib = { path = "../plib" }
clap.workspace = true
libc.workspace = true
gettext-rs.workspace = true
base64 = "0.21"

[[bin]]
name = "cksum"
path = "./cksum.rs"

[[bin]]
name = "uncompress"
path = "./uncompress.rs"

[[bin]]
name = "compress"
path = "./compress.rs"

[[bin]]
name = "uudecode"
path = "./uudecode.rs"

[[bin]]
name = "uuencode"
path = "./uuencode.rs"

[lints]
workspace = true
