name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Fetch
      run: cargo fetch
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --release --verbose

  macos-homebrew:

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sfackler/actions/rustup@master
      - run: echo "version=$(rustc --version)" >> $GITHUB_OUTPUT
        id: rust-version
      - uses: actions/cache@v4
        with:
          path: ~/.cargo/registry/index
          key: index-${{ runner.os }}-${{ github.run_number }}
          restore-keys: |
            index-${{ runner.os }}-
      - run: cargo generate-lockfile
      - uses: actions/cache@v4
        with:
          path: ~/.cargo/registry/cache
          key: registry-${{ runner.os }}-${{ steps.rust-version.outputs.version }}-${{ hashFiles('Cargo.lock') }}
      - name: Fetch
        run: cargo fetch
      - name: Build
        run: cargo build --release --verbose
      - name: Run tests
        run: cargo test --release --verbose

  secondary-platforms:
    steps:
      - uses: actions/checkout@v4
      - run: cargo fetch
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.job.target }}
      - run: cargo ${{ matrix.job.command }} ${{ matrix.job.excludes }} --release --target ${{ matrix.job.target }} --verbose --workspace
    strategy:
      matrix:
        job:
          - {
              command: check,
              target: aarch64-unknown-linux-gnu,
              excludes: "--exclude posixutils-awk --exclude posixutils-m4 --exclude posixutils-tree",
            }
          - {
              command: check,
              target: aarch64-unknown-linux-musl,
              excludes: "--exclude posixutils-awk --exclude posixutils-m4 --exclude posixutils-sys --exclude posixutils-tree",
            }
          - {
              command: build,
              target: x86_64-unknown-linux-musl,
              excludes: "--exclude posixutils-sys",
            }
    runs-on: ubuntu-latest
